"""Task runner — builds the graph once and executes individual task requests.

This is the single place that wires together:
  - the LLM model (get_model)
  - the compiled LangGraph (build_graph)
  - the conversation context loader (get_context)
  - the message persistence helpers (add_user_message, add_ai_message)

Public API
----------
run_task(prompt, req_id, task_id)
    Execute one user prompt through the agent graph and persist the result.
    Pass task_id="" for a brand-new task; pass an existing task_id to continue
    the same conversation thread (follow-up).
"""

from graphs.main_agent_graph import build_graph
from logger import logger
from models.model import get_model
from services.context import add_ai_message, add_user_message, get_context

# ---------------------------------------------------------------------------
# Graph singleton — built once at first call, reused for every request
# ---------------------------------------------------------------------------

_graph = None


def _get_graph():
    """Return the compiled LangGraph, building it on first call."""
    global _graph
    if _graph is None:
        _graph = build_graph(get_model())
    return _graph


def warmup() -> None:
    """Pre-build the graph at startup so the first request isn't slow."""
    _get_graph()


# ---------------------------------------------------------------------------
# Core task runner
# ---------------------------------------------------------------------------

async def run_task(prompt: str, req_id: str, task_id: str = "") -> str:
    """Execute one user prompt and return the final response text.

    Parameters
    ----------
    prompt:
        The user's message for this turn.
    req_id:
        Transient WebSocket key generated by the backend. Published in every
        kernel event so the backend can route it to the right WS connection.
    task_id:
        Empty string  → brand-new task; the graph will create a new task
                        document in MongoDB and assign a fresh task_id.
        Non-empty str → follow-up; the graph reuses the existing document
                        and the LLM receives the full prior message history.

    Returns
    -------
    str
        The final markdown response produced by the response_node.
    """
    graph = _get_graph()

    # For follow-ups, load the prior conversation so the LLM has context.
    # For new tasks, start with an empty message list.
    messages = await get_context(task_id) if task_id else []

    result = await graph.ainvoke(
        {
            "req_id": req_id,
            "messages": messages,
            "task_id": task_id,   # "" → new task, non-empty → follow-up
            "task": prompt,
            "plan": [],
            "current_agent": 0,
            "results": {},
            "response": "",
        }
    )

    final_task_id = result["task_id"]
    response = result["response"]

    # Persist this turn's human + AI messages into the task document
    await add_user_message(final_task_id, prompt)
    await add_ai_message(final_task_id, response)

    logger.info("Task %s completed. Plan: %s", final_task_id, result.get("plan"))
    return response
