"""Kernel entry point.

Connects to MongoDB and Redis, then subscribes to the 'backend_tasks'
channel. Every task.REQUESTED message is handled by run_task().

run_task() is the only public interface:
  - New task:     task_id is "" → graph creates a new task_id in MongoDB
  - Follow-up:    task_id is provided → graph reuses the existing document
"""

import asyncio
import sys

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

from DB.mongodb import mongo_client
from Redis.redis_connection import close, publish, redis_client, subscribe
from graphs.main_agent_graph import build_graph
from logger import logger
from models.model import get_model
from services.context import add_ai_message, add_user_message, get_context

# ---------------------------------------------------------------------------
# Build the graph once at startup (model is a lazy singleton)
# ---------------------------------------------------------------------------

_graph = None


def _get_graph():
    global _graph
    if _graph is None:
        _graph = build_graph(get_model())
    return _graph


# ---------------------------------------------------------------------------
# Core task runner
# ---------------------------------------------------------------------------

async def run_task(prompt: str, req_id: str, task_id: str = "") -> str:
    """Execute one user prompt and return the final response text.

    Parameters
    ----------
    prompt:  the user's message
    req_id:  the transient WebSocket key (generated by the backend)
    task_id: if non-empty, continue an existing task (follow-up); otherwise
             the graph will create a brand-new task document in MongoDB.
    """
    graph = _get_graph()

    # Load existing conversation history so the LLM has context
    messages = await get_context(task_id) if task_id else []

    result = await graph.ainvoke(
        {
            "req_id": req_id,
            "messages": messages,
            "task_id": task_id,        # "" → new task; non-empty → follow-up
            "task": prompt,
            "plan": [],
            "current_agent": 0,
            "results": {},
            "response": "",
        }
    )

    final_task_id = result["task_id"]
    response = result["response"]

    # Persist the new turn (human + ai) into the task's messages array
    await add_user_message(final_task_id, prompt)
    await add_ai_message(final_task_id, response)

    logger.info("Task %s completed. Plan: %s", final_task_id, result.get("plan"))
    return response


# ---------------------------------------------------------------------------
# Redis subscriber — dispatches backend_tasks events
# ---------------------------------------------------------------------------

async def handle_backend_task(data: dict) -> None:
    logger.info(
        "Backend task received | event=%s req_id=%s",
        data.get("event"),
        data.get("req_id"),
    )

    if data.get("event") != "task.REQUESTED":
        return

    req_id = data.get("req_id", "")
    prompt = data.get("prompt", "")
    task_id = data.get("task_id", "")   # "" for new tasks, set for follow-ups

    try:
        await run_task(prompt=prompt, req_id=req_id, task_id=task_id)
    except Exception as exc:
        logger.exception("Error executing task %s: %s", req_id, exc)
        await publish(
            "kernel_events",
            {
                "event": "agent.FAILED",
                "req_id": req_id,
                "task_id": task_id,
                "error": str(exc),
            },
        )


# ---------------------------------------------------------------------------
# Startup
# ---------------------------------------------------------------------------

async def main() -> None:
    # Verify connections
    try:
        await mongo_client.admin.command("ping")
        logger.info("MongoDB connection established")
    except Exception as exc:
        logger.exception("MongoDB connection failed: %s", exc)
        raise

    try:
        await redis_client.ping()
        logger.info("Redis connection established")
    except Exception as exc:
        logger.exception("Redis connection failed: %s", exc)
        raise

    # Warm up model + graph
    _get_graph()
    logger.info("Kernel ready — listening on 'backend_tasks'")

    await subscribe("backend_tasks", handle_backend_task)


if __name__ == "__main__":
    asyncio.run(main())
